title: LexiconMonoSeq, DOM Text based MSA visualization written in Javascript
logo: /images/example5.gif
image: /images/example5.gif
description: LexiconMonoSeq, DOM Text based MSA visualization written in Javascript
show_downloads: true
google_analytics: UA-105632327-1
theme: jekyll-theme-minimal
url: https://ibrahimtanyalcin.github.io/lexicon-mono-seq/
author: 
  twitter: ibrhmTanyalcin
twitter: 
  username: ibrhmTanyalcin
  card: summary
plugins:
  - jekyll-seo-tag
  - jekyll-mentions
jekyll-mentions:
  base_url: https://twitter.com
social:
  name: Ibrahim Tanyalcin
  links:
    - https://twitter.com/ibrhmTanyalcin
    - https://github.com/IbrahimTanyalcin
    - https://www.linkedin.com/in/ibrahimtanyalcin/